# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLAD_config = debug
  ImGui_config = debug
  Fire_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GLAD_config = release
  ImGui_config = release
  Fire_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  GLAD_config = dist
  ImGui_config = dist
  Fire_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLAD ImGui Fire Sandbox

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLAD ImGui

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C Fire/vendor/glad -f Makefile config=$(GLAD_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Fire/vendor/imgui-docking -f Makefile config=$(ImGui_config)
endif

Fire: GLAD ImGui
ifneq (,$(Fire_config))
	@echo "==== Building Fire ($(Fire_config)) ===="
	@${MAKE} --no-print-directory -C Fire -f Makefile config=$(Fire_config)
endif

Sandbox: Fire GLAD
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Fire/vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Fire/vendor/imgui-docking -f Makefile clean
	@${MAKE} --no-print-directory -C Fire -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLAD"
	@echo "   ImGui"
	@echo "   Fire"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"